### ISSUE TITLE
Grace Roadmap 

### ISSUE THREAD

**Issue by RusseII** [RusseII/reading#1]
# Github 
* [ ] https://docs.github.com/en/get-started/quickstart/hello-world
* [ ] https://www.youtube.com/watch?v=w3jLJU7DT5E
* [ ] https://www.youtube.com/watch?v=wpISo9TNjfU
* [ ] https://www.youtube.com/watch?v=RGOj5yH7evk
* [ ] Push some of the code you wrote to github. Make some edits then push the updated code. 

# Hosting (Vercel) 
Vercel can be used to make your websites available to the world. 
* [ ] https://vercel.com/docs/get-started follow this guide to deploy one of your websites. Send russell the deployed URL

**Comment by Bookcliff** [comment]
General wedding info (date, location, colors, etc.) - one webpage
Wedding party info - one webpage
Add an RSVP form with a validating database - separate webpage
Wedding invite - w/custom link
Russell wants pictures - one webpage (allow people to upload photos?)
Add access NFT - one webpage
